global using Narumikazuchi.Singletons;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.IO.MemoryMappedFiles;
global using System.Text;